import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ash',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: '007 Lego Car',
      category: 'toy',
      image: '/images/007Car.PNG',
      price: 120,
      countInStock: 10,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Aquaman Action Figure',
      category: 'toy',
      image: '/images/AquamanAF.PNG',
      price: 100,
      countInStock: 20,
      brand: 'DC',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Batman Action Figure',
      category: 'toy',
      image: '/images/BatmanStrech.PNG',
      price: 220,
      countInStock: 0,
      brand: 'DC',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Cyborg Action Figure',
      category: 'toy',
      image: '/images/CyborgAF.PNG',
      price: 78,
      countInStock: 15,
      brand: 'DC',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Lamborghini Lego',
      category: 'toy',
      image: '/images/Lambo.PNG',
      price: 365,
      countInStock: 5,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lego Bat Mask',
      category: 'toy',
      image: '/images/LegoBatHead.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Lego BatJoker',
      category: 'toy',
      image: '/images/LegoBat_jocker.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Batmobile',
      category: 'toy',
      image: '/images/Batmobile.PNG',
      price: 139,
      countInStock: 12,
      brand: 'DC',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Electronic',
      category: 'toy',
      image: '/images/Elec.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'Doll',
      category: 'toy',
      image: '/images/Doll.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'ED',
      category: 'toy',
      image: '/images/Ed.jpg',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
    {
      name: 'Mario',
      category: 'toy',
      image: '/images/mario03.png',
      price: 19,
      countInStock: 22,
      brand: 'DC',
      rating: 4.2,
      numReviews: 215,
      description: 'high quality product',
    },
  ],
};
export default data;
