const data = {
  products: [
    {
      _id: '1',
      name: '007 Lego Car',
      category: 'toy',
      image: '/images/007Car.PNG',
      price: 120,
      countInStock: 10,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Aquaman Action Figure',
      category: 'toy',
      image: '/images/AquamanAF.PNG',
      price: 100,
      countInStock: 20,
      brand: 'DC',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Batman Action Figure',
      category: 'toy',
      image: '/images/BatmanStrech.PNG',
      price: 220,
      countInStock: 0,
      brand: 'DC',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Cyborg Action Figure',
      category: 'toy',
      image: '/images/CyborgAF.PNG',
      price: 78,
      countInStock: 15,
      brand: 'DC',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Lamborghini Lego',
      category: 'toy',
      image: '/images/Lambo.PNG',
      price: 365,
      countInStock: 5,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Lego BatJoker',
      category: 'toy',
      image: '/images/LegoBat_jocker.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '7',
      name: 'Batmobile',
      category: 'toy',
      image: '/images/Batmobile.PNG',
      price: 139,
      countInStock: 12,
      brand: 'DC',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      _id: '8',
      name: 'Lego Bat Mask',
      category: 'toy',
      image: '/images/LegoBatHead.PNG',
      price: 139,
      countInStock: 12,
      brand: 'Lego',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
